export const space = {
  half_space: "0.25rem",
  one_space: "0.5rem",
  one_half_space: "0.75rem",
  two_space: "1rem",
  two_half_space: "1.25rem",
  three_space: "1.5rem",
  three_half_space: "1.75rem",
  four_space: "2rem",
  four_half_space: "2.25rem",
  five_space: "2.5rem",
  five_half_space: "2.75rem",
  six_space: "3rem",
  seven_space: "3.5rem",
  eight_space: "4rem",
  ten_space: "6rem",
  twelve_space: "8rem",
  fourteen_space: "10rem",
  sixteen_space: "12rem",
  eighteen_space: "14rem",
  twenty_space: "16rem",
};
