export enum Examination {
  CHECK_UP = "CHECK_UP",
  FOLLOW_UP = "FOLLOW_UP",
  ROUTINE = "ROUTINE",
  URGENT = "URGENT",
  EMERGENCY = "EMERGENCY",
  LAB_TESTS = "LAB_TESTS",
  X_RAY = "X_RAY",
  ULTRASOUND = "ULTRASOUND",
  SURGERY = "SURGERY",
  VACCINATION = "VACCINATION",
}
